apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "audit.fullname" . }}
  labels:
    app: {{ template "audit.name" . }}
    chart: {{ template "audit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ template "bc.default.replicas" }}
  selector:
    matchLabels:
      app: {{ template "audit.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "audit.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: hawk-trunk-nexus.stwan.bits/bodhi/audit
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: {{ include "bc.default.ports" . | indent 10 }}
          livenessProbe: {{ include "bc.service.liveness" . | indent 10}}
          readinessProbe: {{ include "bc.default.readiness" . | indent 10}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${BASE_ENV},devtest
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: INFO_VERSION
              value: master
            - name: JAVA_OPTS
              value: -Xmx250m
            - name: SERVER_PORT
              value: 0
          volumeMounts:
            - name: audit_volume
              value: /var
      affinity: {{include "bc.default.affinity" . | indent 6}}
    volumes:
      name: audit-volume
      persistentVolumeClaim:
        claimName: audit-volume-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-volume-pvc
  labels:
    app: {{ template "audit.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

#Todo - logging, networks, constraints, health-checks