apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gisDbUtils.fullname" . }}
  labels:
    app: {{ template "gisDbUtils.name" . }}
    chart: {{ template "gisDbUtils.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ template "bc.default.replicas" }}
  selector:
    matchLabels:
      app: {{ template "gisDbUtils.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gisDbUtils.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: hawk-trunk-nexus.stwan.bits/bodhi/gis-dbutils
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: {{ include "bc.default.ports" . | indent 10 }}
          livenessProbe: {{ include "bc.service.liveness" . | indent 10}}
          readinessProbe: {{ include "bc.default.readiness" . | indent 10}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${BASE_ENV},devtest,postgres_pw
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: JAVA_OPTS
              value: -Xmx250m
            - name: SERVER_PORT
              value:  0
            - name: INFO_VERSION
              value: master
            - name: RDS_POSTGRES_USER
              value: black_user
            - name: RDS_POSTGRES_HOST
              value: ${RDS_HOST}
            - name: RDS_POSTGRES_DB
              value: gis_utils_database
      affinity: {{include "bc.default.affinity" . | indent 6}}
      
          

#Todo - logging, networks, health-checks, constraints